rules: 
  no-ids:
    - 1
  no-important:
    - 0
  final-newline:
    - 0
  clean-import-paths:
    - 0
  property-sort-order:
    - 1
  indentation:
    - 2
    -
      size: 4

  nesting-depth:
    - 1
    -
      max-depth: 4

leading-underscore: false

files:
  ignore:
    - 'app/theme/_mixins.scss'
    - 'node_modules/**/*.*'