//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squidex.Domain.Apps.Core.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Squidex.Domain.Apps.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ScriptingAssetContentAppUrl {
            get {
                return ResourceManager.GetString("ScriptingAssetContentAppUrl", resourceCulture);
            }
        }
        
        internal static string ScriptingAssetContentSlugUrl {
            get {
                return ResourceManager.GetString("ScriptingAssetContentSlugUrl", resourceCulture);
            }
        }
        
        internal static string ScriptingAssetContentUrl {
            get {
                return ResourceManager.GetString("ScriptingAssetContentUrl", resourceCulture);
            }
        }
        
        internal static string ScriptingCharacterCount {
            get {
                return ResourceManager.GetString("ScriptingCharacterCount", resourceCulture);
            }
        }
        
        internal static string ScriptingComplete {
            get {
                return ResourceManager.GetString("ScriptingComplete", resourceCulture);
            }
        }
        
        internal static string ScriptingContentAction {
            get {
                return ResourceManager.GetString("ScriptingContentAction", resourceCulture);
            }
        }
        
        internal static string ScriptingContentUrl {
            get {
                return ResourceManager.GetString("ScriptingContentUrl", resourceCulture);
            }
        }
        
        internal static string ScriptingDeleteJson {
            get {
                return ResourceManager.GetString("ScriptingDeleteJson", resourceCulture);
            }
        }
        
        internal static string ScriptingDisallow {
            get {
                return ResourceManager.GetString("ScriptingDisallow", resourceCulture);
            }
        }
        
        internal static string ScriptingFormatDate {
            get {
                return ResourceManager.GetString("ScriptingFormatDate", resourceCulture);
            }
        }
        
        internal static string ScriptingFormatTime {
            get {
                return ResourceManager.GetString("ScriptingFormatTime", resourceCulture);
            }
        }
        
        internal static string ScriptingGenerate {
            get {
                return ResourceManager.GetString("ScriptingGenerate", resourceCulture);
            }
        }
        
        internal static string ScriptingGetJSON {
            get {
                return ResourceManager.GetString("ScriptingGetJSON", resourceCulture);
            }
        }
        
        internal static string ScriptingGuid {
            get {
                return ResourceManager.GetString("ScriptingGuid", resourceCulture);
            }
        }
        
        internal static string ScriptingHtml2Text {
            get {
                return ResourceManager.GetString("ScriptingHtml2Text", resourceCulture);
            }
        }
        
        internal static string ScriptingMarkdown2Text {
            get {
                return ResourceManager.GetString("ScriptingMarkdown2Text", resourceCulture);
            }
        }
        
        internal static string ScriptingMD5 {
            get {
                return ResourceManager.GetString("ScriptingMD5", resourceCulture);
            }
        }
        
        internal static string ScriptingPatchJson {
            get {
                return ResourceManager.GetString("ScriptingPatchJson", resourceCulture);
            }
        }
        
        internal static string ScriptingPostJSON {
            get {
                return ResourceManager.GetString("ScriptingPostJSON", resourceCulture);
            }
        }
        
        internal static string ScriptingPutJson {
            get {
                return ResourceManager.GetString("ScriptingPutJson", resourceCulture);
            }
        }
        
        internal static string ScriptingReject {
            get {
                return ResourceManager.GetString("ScriptingReject", resourceCulture);
            }
        }
        
        internal static string ScriptingReplace {
            get {
                return ResourceManager.GetString("ScriptingReplace", resourceCulture);
            }
        }
        
        internal static string ScriptingSHA256 {
            get {
                return ResourceManager.GetString("ScriptingSHA256", resourceCulture);
            }
        }
        
        internal static string ScriptingSHA512 {
            get {
                return ResourceManager.GetString("ScriptingSHA512", resourceCulture);
            }
        }
        
        internal static string ScriptingSlugify {
            get {
                return ResourceManager.GetString("ScriptingSlugify", resourceCulture);
            }
        }
        
        internal static string ScriptingToCamelCase {
            get {
                return ResourceManager.GetString("ScriptingToCamelCase", resourceCulture);
            }
        }
        
        internal static string ScriptingToPascalCase {
            get {
                return ResourceManager.GetString("ScriptingToPascalCase", resourceCulture);
            }
        }
        
        internal static string ScriptingTranslate {
            get {
                return ResourceManager.GetString("ScriptingTranslate", resourceCulture);
            }
        }
        
        internal static string ScriptingWordCount {
            get {
                return ResourceManager.GetString("ScriptingWordCount", resourceCulture);
            }
        }
        
        internal static string ScriptingRequestAsync {
            get {
                return ResourceManager.GetString("ScriptingRequestAsync", resourceCulture);
            }
        }
    }
}
