//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squidex.Domain.Apps.Core.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squidex.Domain.Apps.Core.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The download URL to the asset..
    /// </summary>
    internal static string ScriptingAssetContentAppUrl {
        get {
            return ResourceManager.GetString("ScriptingAssetContentAppUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The download URL to the asset using the file slug instead of the ID..
    /// </summary>
    internal static string ScriptingAssetContentSlugUrl {
        get {
            return ResourceManager.GetString("ScriptingAssetContentSlugUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The download URL to the asset without the app name (deprecated)..
    /// </summary>
    internal static string ScriptingAssetContentUrl {
        get {
            return ResourceManager.GetString("ScriptingAssetContentUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Counts the number of characters in a text. Useful in combination with html2Text or markdown2Text..
    /// </summary>
    internal static string ScriptingCharacterCount {
        get {
            return ResourceManager.GetString("ScriptingCharacterCount", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Completes the script when an async method is used..
    /// </summary>
    internal static string ScriptingComplete {
        get {
            return ResourceManager.GetString("ScriptingComplete", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The status of the content..
    /// </summary>
    internal static string ScriptingContentAction {
        get {
            return ResourceManager.GetString("ScriptingContentAction", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The URL to the content in the UI..
    /// </summary>
    internal static string ScriptingContentUrl {
        get {
            return ResourceManager.GetString("ScriptingContentUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Makes a DELETE request to the defined URL and parses the result as JSON. Headers are optional..
    /// </summary>
    internal static string ScriptingDeleteJson {
        get {
            return ResourceManager.GetString("ScriptingDeleteJson", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tell Squidex to not allow the current operation and to return a 400 (BadRequest)..
    /// </summary>
    internal static string ScriptingDisallow {
        get {
            return ResourceManager.GetString("ScriptingDisallow", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Formats a JavaScript date object using the specified pattern..
    /// </summary>
    internal static string ScriptingFormatDate {
        get {
            return ResourceManager.GetString("ScriptingFormatDate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Formats a JavaScript date object using the specified pattern..
    /// </summary>
    internal static string ScriptingFormatTime {
        get {
            return ResourceManager.GetString("ScriptingFormatTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Makes a GET request to the defined URL and parses the result as JSON. Headers are optional..
    /// </summary>
    internal static string ScriptingGetJSON {
        get {
            return ResourceManager.GetString("ScriptingGetJSON", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Generates a guid..
    /// </summary>
    internal static string ScriptingGuid {
        get {
            return ResourceManager.GetString("ScriptingGuid", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converts a HTML string to plain text..
    /// </summary>
    internal static string ScriptingHtml2Text {
        get {
            return ResourceManager.GetString("ScriptingHtml2Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converts a markdown string to plain text..
    /// </summary>
    internal static string ScriptingMarkdown2Text {
        get {
            return ResourceManager.GetString("ScriptingMarkdown2Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Calculate the MD5 hash from a given string. Use this method for hashing passwords, when backwards compatibility is important..
    /// </summary>
    internal static string ScriptingMD5 {
        get {
            return ResourceManager.GetString("ScriptingMD5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Makes a PATCH request to the defined URL and parses the result as JSON. Headers are optional..
    /// </summary>
    internal static string ScriptingPatchJson {
        get {
            return ResourceManager.GetString("ScriptingPatchJson", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Makes a POST request to the defined URL and parses the result as JSON. Headers are optional..
    /// </summary>
    internal static string ScriptingPostJSON {
        get {
            return ResourceManager.GetString("ScriptingPostJSON", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Makes a PUT request to the defined URL and parses the result as JSON. Headers are optional..
    /// </summary>
    internal static string ScriptingPutJson {
        get {
            return ResourceManager.GetString("ScriptingPutJson", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tell Squidex to reject the current operation and to return a 403 (Forbidden)..
    /// </summary>
    internal static string ScriptingReject {
        get {
            return ResourceManager.GetString("ScriptingReject", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tell Squidex that you have modified the data and that the change should be applied..
    /// </summary>
    internal static string ScriptingReplace {
        get {
            return ResourceManager.GetString("ScriptingReplace", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Calculate the SHA256 hash from a given string. Use this method for hashing passwords..
    /// </summary>
    internal static string ScriptingSHA256 {
        get {
            return ResourceManager.GetString("ScriptingSHA256", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Calculate the SHA256 hash from a given string. Use this method for hashing passwords..
    /// </summary>
    internal static string ScriptingSHA512 {
        get {
            return ResourceManager.GetString("ScriptingSHA512", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Calculates the slug of a text by removing all special characters and whitespaces to create a friendly term that can be used for SEO-friendly URLs..
    /// </summary>
    internal static string ScriptingSlugify {
        get {
            return ResourceManager.GetString("ScriptingSlugify", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converts a text to camelCase..
    /// </summary>
    internal static string ScriptingToCamelCase {
        get {
            return ResourceManager.GetString("ScriptingToCamelCase", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Converts a text to PascalCase.
    /// </summary>
    internal static string ScriptingToPascalCase {
        get {
            return ResourceManager.GetString("ScriptingToPascalCase", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Counts the number of words in a text. Useful in combination with html2Text or markdown2Text..
    /// </summary>
    internal static string ScriptingWordCount {
        get {
            return ResourceManager.GetString("ScriptingWordCount", resourceCulture);
        }
    }
}
