//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squidex.Domain.Apps.Entities.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squidex.Domain.Apps.Entities.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Queries the asset with the specified ID and invokes the callback with an array of assets..
    /// </summary>
    internal static string ScriptingGetAsset {
        get {
            return ResourceManager.GetString("ScriptingGetAsset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Queries the assets with the specified IDs and invokes the callback with an array of assets..
    /// </summary>
    internal static string ScriptingGetAssets {
        get {
            return ResourceManager.GetString("ScriptingGetAssets", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Get the text of an asset. Encodings: base64,ascii,unicode,utf8.
    /// </summary>
    internal static string ScriptingGetAssetText {
        get {
            return ResourceManager.GetString("ScriptingGetAssetText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Gets the blur hash of an asset if it is an image or null otherwise..
    /// </summary>
    internal static string ScriptingGetBlurHash {
        get {
            return ResourceManager.GetString("ScriptingGetBlurHash", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Queries the content item with the specified ID and invokes the callback with an array of contents..
    /// </summary>
    internal static string ScriptingGetReference {
        get {
            return ResourceManager.GetString("ScriptingGetReference", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Queries the content items with the specified IDs and invokes the callback with an array of contents..
    /// </summary>
    internal static string ScriptingGetReferences {
        get {
            return ResourceManager.GetString("ScriptingGetReferences", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Increments the counter with the given name and returns the value (OBSOLETE)..
    /// </summary>
    internal static string ScriptingIncrementCounter {
        get {
            return ResourceManager.GetString("ScriptingIncrementCounter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Increments the counter with the given name and returns the value..
    /// </summary>
    internal static string ScriptingIncrementCounterV2 {
        get {
            return ResourceManager.GetString("ScriptingIncrementCounterV2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Resets the counter with the given name to zero (OBSOLETE)..
    /// </summary>
    internal static string ScriptingResetCounter {
        get {
            return ResourceManager.GetString("ScriptingResetCounter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Resets the counter with the given name to zero..
    /// </summary>
    internal static string ScriptingResetCounterV2 {
        get {
            return ResourceManager.GetString("ScriptingResetCounterV2", resourceCulture);
        }
    }
}
