//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squidex.Infrastructure.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squidex.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Json query not valid: {0}..
    /// </summary>
    internal static string QueryInvalid {
        get {
            return ResourceManager.GetString("QueryInvalid", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Array value is not allowed for &apos;{0}&apos; operator and path &apos;{1}&apos;..
    /// </summary>
    internal static string QueryInvalidArray {
        get {
            return ResourceManager.GetString("QueryInvalidArray", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Json query not valid json: {0}..
    /// </summary>
    internal static string QueryInvalidJson {
        get {
            return ResourceManager.GetString("QueryInvalidJson", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Either &apos;and&apos;, &apos;or&apos;, &apos;not&apos; or &apos;path&apos;+&apos;op&apos; must be set..
    /// </summary>
    internal static string QueryInvalidJsonStructure {
        get {
            return ResourceManager.GetString("QueryInvalidJsonStructure", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid operator for type {1} at &apos;{2}&apos;..
    /// </summary>
    internal static string QueryInvalidOperator {
        get {
            return ResourceManager.GetString("QueryInvalidOperator", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Path &apos;{0}&apos; does not point to a valid property in the model..
    /// </summary>
    internal static string QueryInvalidPath {
        get {
            return ResourceManager.GetString("QueryInvalidPath", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} is not a valid regular expression at path &apos;{1}&apos;..
    /// </summary>
    internal static string QueryInvalidRegex {
        get {
            return ResourceManager.GetString("QueryInvalidRegex", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected {0} for path &apos;{2}&apos;, but got {1}..
    /// </summary>
    internal static string QueryWrongExpectedType {
        get {
            return ResourceManager.GetString("QueryWrongExpectedType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected {0} for path &apos;{1}&apos;, but got invalid String..
    /// </summary>
    internal static string QueryWrongFormat {
        get {
            return ResourceManager.GetString("QueryWrongFormat", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Expected primitive for path &apos;{1}&apos;, but got {0}..
    /// </summary>
    internal static string QueryWrongPrimitive {
        get {
            return ResourceManager.GetString("QueryWrongPrimitive", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Unsupported type {0} for path &apos;{1}&apos;..
    /// </summary>
    internal static string QueryWrongType {
        get {
            return ResourceManager.GetString("QueryWrongType", resourceCulture);
        }
    }
}
