apiVersion: v1
kind: ConfigMap
metadata:
  name: squidex
data:
  MONGODB__CONFIGURATION: mongodb+srv://{{ .Values.mongoconnectionstring}}@{{ .Values.mongourl }}/?retryWrites=true&w=majority
  DOMAIN: {{ .Values.domain }}
  ADMIN_EMAIL: {{ .Values.adminEmail }}
  S3_BUCKET: {{ .Values.S3Bucket }}
  CONTENTS__USETRANSACTIONS: "{{ .Values.useTransactions }}"
  FULLTEXT__ELASTIC__OPENSEARCH: "true"