apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:

  consul-template-config.hcl: |-
    vault {
      renew_token = false
      vault_agent_token_file = "/home/vault/.vault-token"
      retry {
        backoff = "1s"
      }
    }

    template {
      destination = "/etc/secrets/appsettings.secrets.json"
      contents = <<EOH
      {
        "eventStore": {
          "mongoDb": {
            {{ "{{- with secret " }}{{ .Values.configmap.VaultSecretPath | quote }} }}
            "configuration": "mongodb+srv://{{ "{{ .Data.data.mongoUser }}" }}:{{ "{{ .Data.data.mongoPassword }}" }}@{{ .Values.configmap.mongoDb }}"
            {{ "{{ end }}" }}
          }
        },  
  
        "store": {
          "mongoDb": {
            {{ "{{- with secret " }}{{ .Values.configmap.VaultSecretPath | quote }} }}
            "configuration": "mongodb+srv://{{ "{{ .Data.data.mongoUser }}" }}:{{ "{{ .Data.data.mongoPassword }}" }}@{{ .Values.configmap.mongoDb }}"
            {{ "{{ end }}" }}
          }
        }
      }
      EOH
    }

  vault-agent-config.hcl: |-
    # Uncomment this to have Agent run once (e.g. when running as an initContainer)
    exit_after_auth = true
    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = {{ .Values.configmap.VaultK8sAuthPath | quote }}
            config = {
                role = {{ .Values.configmap.VaultK8sRoleName | quote }}
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }
  