apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "cosmos.fullname" . }}-ingress
  labels:
    app: {{ include "cosmos.fullname" . }}
  annotations:
  {{- if .Values.ingress }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "cosmos.fullname" . }}
          servicePort: {{ .Values.service.port_name }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}