{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "cosmos.fullname" . }}
data:
{{- range $filename, $fileContents := .Values.secrets.secretFiles }}
  {{ $filename }}: {{ $fileContents | b64enc | quote }}
{{- end }}
{{- end }}