const constants = {
  editorWelcomeMessage: 'Hi Vega Test. Editor',
  reviewerWelcomeMessage: 'Hi Vega Test. Reviewer',
  commentaryType: 'Price Commentary',
  commodity: 'Styrene',
  region: 'Middle East',
  contentBody: 'This is content creation test',
  boldCommentary: 'Bold Letters Commentary Test',
  italicCommentary: 'Italic Commentary Test',
  bulletPoints: 'Bullet Point Test',
  numberedList: 'Numbered List Test',
  alertSuccessMessage: 'Contents created successfully.',
  partialCommentaryTypeText: 'Price',
  partialCommodityText: 'Tolu',
  partialRegionText: 'Latin',
  invalidRefDataText: 'invalid',
  failureMessage: 'Content element not valid, please check the field with the red bar on the left in all languages (if localizable).',
  validationErrorMessage: 'A content item with these values already exists.',
  duplicateTestCommodity: 'Propylene',
  duplicateTestCommentaryType: 'Analyst Commentary',
  duplicateTestRegion: 'South East Asia & Pacific',
  duplicateTestContentBody: 'This is duplicate creation test',
  editorUrl: 'http://localhost:5000/editors/toastui/md-editor.html',
  contentCommodity: ' Commodity  ',
  contentCommentaryType: ' Commentary Type  ',
  contentRegion: ' Region  ',
  editorOptionsBold: 'tui-bold tui-toolbar-icons',
  editorOptionsItalic: 'tui-italic tui-toolbar-icons',
  editorOptionsNumberedList: 'tui-ol tui-toolbar-icons',
  editorOptionsBulletPointList: 'tui-ul tui-toolbar-icons'
};
export default constants;
