//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squidex.Domain.Apps.Core; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class FieldDescriptions {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal FieldDescriptions() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squidex.Domain.Apps.Core.FieldDescriptions", typeof(FieldDescriptions).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The user or client that triggered the event or command..
    /// </summary>
    public static string Actor {
        get {
            return ResourceManager.GetString("Actor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of this actor..
    /// </summary>
    public static string ActorIdentifier {
        get {
            return ResourceManager.GetString("ActorIdentifier", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The type of this actor..
    /// </summary>
    public static string ActorType {
        get {
            return ResourceManager.GetString("ActorType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of the current app..
    /// </summary>
    public static string AppId {
        get {
            return ResourceManager.GetString("AppId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The name of the current app..
    /// </summary>
    public static string AppName {
        get {
            return ResourceManager.GetString("AppName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The asset..
    /// </summary>
    public static string Asset {
        get {
            return ResourceManager.GetString("Asset", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The hash of the file. Can be null for old files..
    /// </summary>
    public static string AssetFileHash {
        get {
            return ResourceManager.GetString("AssetFileHash", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file name of the asset..
    /// </summary>
    public static string AssetFileName {
        get {
            return ResourceManager.GetString("AssetFileName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The size of the file in bytes..
    /// </summary>
    public static string AssetFileSize {
        get {
            return ResourceManager.GetString("AssetFileSize", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file type (file extension) of the asset..
    /// </summary>
    public static string AssetFileType {
        get {
            return ResourceManager.GetString("AssetFileType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The version of the file..
    /// </summary>
    public static string AssetFileVersion {
        get {
            return ResourceManager.GetString("AssetFileVersion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Determines if the uploaded file is an image..
    /// </summary>
    public static string AssetIsImage {
        get {
            return ResourceManager.GetString("AssetIsImage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to True, when the asset is not public..
    /// </summary>
    public static string AssetIsProtected {
        get {
            return ResourceManager.GetString("AssetIsProtected", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The asset metadata..
    /// </summary>
    public static string AssetMetadata {
        get {
            return ResourceManager.GetString("AssetMetadata", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The type of the image..
    /// </summary>
    public static string AssetMetadataText {
        get {
            return ResourceManager.GetString("AssetMetadataText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The asset metadata with name &apos;name&apos;..
    /// </summary>
    public static string AssetMetadataValue {
        get {
            return ResourceManager.GetString("AssetMetadataValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The mime type..
    /// </summary>
    public static string AssetMimeType {
        get {
            return ResourceManager.GetString("AssetMimeType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of the parent folder. Empty for files without parent..
    /// </summary>
    public static string AssetParentId {
        get {
            return ResourceManager.GetString("AssetParentId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The full path in the folder hierarchy as array of folder infos..
    /// </summary>
    public static string AssetParentPath {
        get {
            return ResourceManager.GetString("AssetParentPath", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The height of the image in pixels if the asset is an image..
    /// </summary>
    public static string AssetPixelHeight {
        get {
            return ResourceManager.GetString("AssetPixelHeight", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The width of the image in pixels if the asset is an image..
    /// </summary>
    public static string AssetPixelWidth {
        get {
            return ResourceManager.GetString("AssetPixelWidth", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The assets..
    /// </summary>
    public static string AssetsItems {
        get {
            return ResourceManager.GetString("AssetsItems", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The file name as slug..
    /// </summary>
    public static string AssetSlug {
        get {
            return ResourceManager.GetString("AssetSlug", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The source URL of the asset..
    /// </summary>
    public static string AssetSourceUrl {
        get {
            return ResourceManager.GetString("AssetSourceUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The total count of assets..
    /// </summary>
    public static string AssetsTotal {
        get {
            return ResourceManager.GetString("AssetsTotal", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The asset tags..
    /// </summary>
    public static string AssetTags {
        get {
            return ResourceManager.GetString("AssetTags", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The thumbnail URL to the asset..
    /// </summary>
    public static string AssetThumbnailUrl {
        get {
            return ResourceManager.GetString("AssetThumbnailUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The type of the asset..
    /// </summary>
    public static string AssetType {
        get {
            return ResourceManager.GetString("AssetType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The URL to the asset..
    /// </summary>
    public static string AssetUrl {
        get {
            return ResourceManager.GetString("AssetUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The executed command..
    /// </summary>
    public static string Command {
        get {
            return ResourceManager.GetString("Command", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The user when someone is mentioned with &apos;@&apos;..
    /// </summary>
    public static string CommentMentionedUser {
        get {
            return ResourceManager.GetString("CommentMentionedUser", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The text of the comment..
    /// </summary>
    public static string CommentText {
        get {
            return ResourceManager.GetString("CommentText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The URL pointing to the source of the comment..
    /// </summary>
    public static string CommentUrl {
        get {
            return ResourceManager.GetString("CommentUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} field ({1} component)..
    /// </summary>
    public static string ComponentField {
        get {
            return ResourceManager.GetString("ComponentField", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The schema id to identity the component type..
    /// </summary>
    public static string ComponentSchemaId {
        get {
            return ResourceManager.GetString("ComponentSchemaId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The content..
    /// </summary>
    public static string Content {
        get {
            return ResourceManager.GetString("Content", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} nested field..
    /// </summary>
    public static string ContentArrayField {
        get {
            return ResourceManager.GetString("ContentArrayField", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The data of the content..
    /// </summary>
    public static string ContentData {
        get {
            return ResourceManager.GetString("ContentData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The previous data of the content..
    /// </summary>
    public static string ContentDataOld {
        get {
            return ResourceManager.GetString("ContentDataOld", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} field..
    /// </summary>
    public static string ContentField {
        get {
            return ResourceManager.GetString("ContentField", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The flat data of the content..
    /// </summary>
    public static string ContentFlatData {
        get {
            return ResourceManager.GetString("ContentFlatData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The new status of the content..
    /// </summary>
    public static string ContentNewStatus {
        get {
            return ResourceManager.GetString("ContentNewStatus", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The new status color of the content..
    /// </summary>
    public static string ContentNewStatusColor {
        get {
            return ResourceManager.GetString("ContentNewStatusColor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to {0} field ({1})..
    /// </summary>
    public static string ContentPartitionField {
        get {
            return ResourceManager.GetString("ContentPartitionField", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The data for the content..
    /// </summary>
    public static string ContentRequestData {
        get {
            return ResourceManager.GetString("ContentRequestData", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The timestamp when the status should be changed..
    /// </summary>
    public static string ContentRequestDueTime {
        get {
            return ResourceManager.GetString("ContentRequestDueTime", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The optional custom content ID..
    /// </summary>
    public static string ContentRequestOptionalId {
        get {
            return ResourceManager.GetString("ContentRequestOptionalId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The initial status..
    /// </summary>
    public static string ContentRequestOptionalStatus {
        get {
            return ResourceManager.GetString("ContentRequestOptionalStatus", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Makes the update as patch..
    /// </summary>
    public static string ContentRequestPatch {
        get {
            return ResourceManager.GetString("ContentRequestPatch", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Set to true to autopublish content on create..
    /// </summary>
    public static string ContentRequestPublish {
        get {
            return ResourceManager.GetString("ContentRequestPublish", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The status for the content..
    /// </summary>
    public static string ContentRequestStatus {
        get {
            return ResourceManager.GetString("ContentRequestStatus", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The display name of the schema..
    /// </summary>
    public static string ContentSchemaDisplayName {
        get {
            return ResourceManager.GetString("ContentSchemaDisplayName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of the schema..
    /// </summary>
    public static string ContentSchemaId {
        get {
            return ResourceManager.GetString("ContentSchemaId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The name of the schema..
    /// </summary>
    public static string ContentSchemaName {
        get {
            return ResourceManager.GetString("ContentSchemaName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The contents..
    /// </summary>
    public static string ContentsItems {
        get {
            return ResourceManager.GetString("ContentsItems", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The status of the content..
    /// </summary>
    public static string ContentStatus {
        get {
            return ResourceManager.GetString("ContentStatus", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The status color of the content..
    /// </summary>
    public static string ContentStatusColor {
        get {
            return ResourceManager.GetString("ContentStatusColor", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The previous status of the content..
    /// </summary>
    public static string ContentStatusOld {
        get {
            return ResourceManager.GetString("ContentStatusOld", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The total count of  contents..
    /// </summary>
    public static string ContentsTotal {
        get {
            return ResourceManager.GetString("ContentsTotal", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The URL to the content..
    /// </summary>
    public static string ContentUrl {
        get {
            return ResourceManager.GetString("ContentUrl", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Validates the content item..
    /// </summary>
    public static string ContentValidate {
        get {
            return ResourceManager.GetString("ContentValidate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The context object holding all values..
    /// </summary>
    public static string Context {
        get {
            return ResourceManager.GetString("Context", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The edit token..
    /// </summary>
    public static string EditToken {
        get {
            return ResourceManager.GetString("EditToken", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The timestamp when the object was created..
    /// </summary>
    public static string EntityCreated {
        get {
            return ResourceManager.GetString("EntityCreated", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The user who created the object..
    /// </summary>
    public static string EntityCreatedBy {
        get {
            return ResourceManager.GetString("EntityCreatedBy", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The expected version..
    /// </summary>
    public static string EntityExpectedVersion {
        get {
            return ResourceManager.GetString("EntityExpectedVersion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of the object (usually GUID)..
    /// </summary>
    public static string EntityId {
        get {
            return ResourceManager.GetString("EntityId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to True when deleted..
    /// </summary>
    public static string EntityIsDeleted {
        get {
            return ResourceManager.GetString("EntityIsDeleted", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The timestamp when the object was updated the last time..
    /// </summary>
    public static string EntityLastModified {
        get {
            return ResourceManager.GetString("EntityLastModified", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The user who updated the object the last time..
    /// </summary>
    public static string EntityLastModifiedBy {
        get {
            return ResourceManager.GetString("EntityLastModifiedBy", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to True when the entity should be deleted permanently..
    /// </summary>
    public static string EntityRequestDeletePermanent {
        get {
            return ResourceManager.GetString("EntityRequestDeletePermanent", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The version of the objec..
    /// </summary>
    public static string EntityVersion {
        get {
            return ResourceManager.GetString("EntityVersion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The actual event..
    /// </summary>
    public static string Event {
        get {
            return ResourceManager.GetString("Event", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The name of the event..
    /// </summary>
    public static string EventName {
        get {
            return ResourceManager.GetString("EventName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The event timestamp..
    /// </summary>
    public static string EventTimestamp {
        get {
            return ResourceManager.GetString("EventTimestamp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The type of the event, e.g. &apos;Created&apos; or &apos;Updated&apos;..
    /// </summary>
    public static string EventType {
        get {
            return ResourceManager.GetString("EventType", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The path to the json value..
    /// </summary>
    public static string JsonPath {
        get {
            return ResourceManager.GetString("JsonPath", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID part of this ID..
    /// </summary>
    public static string NamedId {
        get {
            return ResourceManager.GetString("NamedId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The name part of this ID..
    /// </summary>
    public static string NamedName {
        get {
            return ResourceManager.GetString("NamedName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The current operation..
    /// </summary>
    public static string Operation {
        get {
            return ResourceManager.GetString("Operation", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional OData filter..
    /// </summary>
    public static string QueryFilter {
        get {
            return ResourceManager.GetString("QueryFilter", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Comma separated list of object IDs. Overrides all other query parameters..
    /// </summary>
    public static string QueryIds {
        get {
            return ResourceManager.GetString("QueryIds", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional OData order definition..
    /// </summary>
    public static string QueryOrderBy {
        get {
            return ResourceManager.GetString("QueryOrderBy", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to JSON query as well formatted json string. Overrides all other query parameters, except &apos;ids&apos;..
    /// </summary>
    public static string QueryQ {
        get {
            return ResourceManager.GetString("QueryQ", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional OData full text search..
    /// </summary>
    public static string QuerySearch {
        get {
            return ResourceManager.GetString("QuerySearch", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional number of items to skip..
    /// </summary>
    public static string QuerySkip {
        get {
            return ResourceManager.GetString("QuerySkip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Optional number of items to take..
    /// </summary>
    public static string QueryTop {
        get {
            return ResourceManager.GetString("QueryTop", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The optional version of the content to retrieve an older instance (not cached)..
    /// </summary>
    public static string QueryVersion {
        get {
            return ResourceManager.GetString("QueryVersion", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of the schema..
    /// </summary>
    public static string SchemaId {
        get {
            return ResourceManager.GetString("SchemaId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The referenced assets..
    /// </summary>
    public static string StringFieldAssets {
        get {
            return ResourceManager.GetString("StringFieldAssets", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The referenced content items..
    /// </summary>
    public static string StringFieldReferences {
        get {
            return ResourceManager.GetString("StringFieldReferences", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The text of this field..
    /// </summary>
    public static string StringFieldText {
        get {
            return ResourceManager.GetString("StringFieldText", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The translation status..
    /// </summary>
    public static string TranslationStatus {
        get {
            return ResourceManager.GetString("TranslationStatus", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The translation status ({0})..
    /// </summary>
    public static string TranslationStatusLanguage {
        get {
            return ResourceManager.GetString("TranslationStatusLanguage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The current number of calls..
    /// </summary>
    public static string UsageCallsCurrent {
        get {
            return ResourceManager.GetString("UsageCallsCurrent", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The configured usage limit..
    /// </summary>
    public static string UsageCallsLimit {
        get {
            return ResourceManager.GetString("UsageCallsLimit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Information about the current user..
    /// </summary>
    public static string User {
        get {
            return ResourceManager.GetString("User", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The additional properties of this user..
    /// </summary>
    public static string UserClaims {
        get {
            return ResourceManager.GetString("UserClaims", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The display name of this user..
    /// </summary>
    public static string UserDisplayName {
        get {
            return ResourceManager.GetString("UserDisplayName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The email address ofthis  user..
    /// </summary>
    public static string UserEmail {
        get {
            return ResourceManager.GetString("UserEmail", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The ID of this user..
    /// </summary>
    public static string UserId {
        get {
            return ResourceManager.GetString("UserId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to True when this user is a client, which is typically the case when the request is made from the API..
    /// </summary>
    public static string UserIsClient {
        get {
            return ResourceManager.GetString("UserIsClient", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to True when this user is a user, which is typically the case when the request is made in the UI..
    /// </summary>
    public static string UserIsUser {
        get {
            return ResourceManager.GetString("UserIsUser", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The list of additional properties that have the name &apos;name&apos;..
    /// </summary>
    public static string UsersClaimsValue {
        get {
            return ResourceManager.GetString("UsersClaimsValue", resourceCulture);
        }
    }
}
