export const constants = {
    alertSuccessMessage: 'Contents created successfully.',
    boldCommentary: 'Bold Letters Commentary Test',
    bulletPoints: 'Bullet Point Test',
    commentaryContentText: 'This is commentary edit test',
    commentaryType: 'Price Commentary',
    commodity: 'Styrene',
    contentBody: 'This is content creation test',
    contentCommentaryType: ' Commentary Type  ',
    contentCommodity: ' Commodity  ',
    contentRegion: ' Region  ',
    duplicateTestCommentaryType: 'Analyst Commentary',
    duplicateTestCommodity: 'Propylene',
    duplicateTestContentBody: 'This is duplicate creation test',
    duplicateTestRegion: 'South East Asia & Pacific',
    editContentTestText: 'Editing existing commentary',
    editorOptionsBold: 'tui-bold tui-toolbar-icons',
    editorOptionsBulletPointList: 'tui-ul tui-toolbar-icons',
    editorOptionsItalic: 'tui-italic tui-toolbar-icons',
    editorOptionsNumberedList: 'tui-ol tui-toolbar-icons',
    editorUrl: `${process.env.SQUIDEX_URL}/editors/toastui/md-editor.html`,
    editorWelcomeMessage: 'Hi Vega Test. Editor',
    failureMessage: 'Content element not valid, please check the field with the red bar on the left in all languages (if localizable).',
    invalidRefDataText: 'invalid',
    italicCommentary: 'Italic Commentary Test',
    modifiedCommentaryType: 'Deals Commentary',
    modifiedCommodity: 'Propylene',
    modifiedRegion: 'CIS/Central Asia',
    numberedList: 'Numbered List Test',
    partialCommentaryTypeText: 'Price',
    partialCommodityText: 'Tolu',
    partialRegionText: 'Latin',
    region: 'Middle East',
    reviewerWelcomeMessage: 'Hi Vega Test. Reviewer',
    validationErrorMessage: 'A content item with these values already exists.'
};