apiVersion: v1
kind: Service
metadata:
  name: {{ include "squidex.fullname" . }}
  labels:
    {{- include "squidex.labels" . | indent 4 }}  
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq (lower .Values.service.type) "nodeport") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "squidex.selectors" . | indent 4 }}