services:
  webhookcatcher:
    image: tarampampam/webhook-tester:2
    command: serve --port 1026
    ports:
      - "1026:1026"
    networks:
      - internal
    
networks:
  internal:
    driver: bridge