name: Marketplace - Vultr
concurrency: marketplace-vultr

on:
  release:
    types: [ released ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/vultr.pkr.hcl

  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: packer/vultr.pkr.hcl
        env:
          PACKER_LOG: 1

      - name: Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer/vultr.pkr.hcl
        env:
          PACKER_LOG: 1
          PKR_VAR_squidex_version: "${{ env.GITHUB_REF_SLUG }}"
          VULTR_API_KEY: "${{ secrets.VULTR_API_KEY }}"
